// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-IiKTxxB0FZz9ACuz8NqxBKN9XLpmjQ',
    appId: '1:1087171713194:web:e4f85256e58a484d2218d3',
    messagingSenderId: '1087171713194',
    projectId: 'students-app-1fecd',
    authDomain: 'students-app-1fecd.firebaseapp.com',
    storageBucket: 'students-app-1fecd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZurCqCYsXZQpOYRudWAkcvhhcHVyTO3c',
    appId: '1:1087171713194:android:839af03f0c674a8d2218d3',
    messagingSenderId: '1087171713194',
    projectId: 'students-app-1fecd',
    storageBucket: 'students-app-1fecd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-IiKTxxB0FZz9ACuz8NqxBKN9XLpmjQ',
    appId: '1:1087171713194:web:a891f433281928072218d3',
    messagingSenderId: '1087171713194',
    projectId: 'students-app-1fecd',
    authDomain: 'students-app-1fecd.firebaseapp.com',
    storageBucket: 'students-app-1fecd.firebasestorage.app',
  );
}
